### ISSUE TITLE
SFINAE test for 'parse' method won't compile

### ISSUE THREAD

**Issue by mcharlou** [sirehna/xdyn#3]
## Expected Behavior
Trying to compile using Code::Blocks IDE, so I expect to manage the compilation at some point.

## Current Behavior
`Fatal error in core/inc/ForceModel.hpp (line 40): expected primary-expression before ')' token`

The error is in the SFINAE test for method 'parse':
```
// SFINAE test for 'parse' method
template<typename T>
struct HasParse
{
    typedef char yes[1];
    typedef char no [2];
    template<typename U> static yes &check(typeof(&U::parse)*); //<-- Error on this line
    template<typename U> static no &check(...);
    static const bool value = sizeof(check<T>(0)) == sizeof(yes);
};
```

## Steps to Reproduce
Compile with GCC 8.3.0

## Context (Environment)
OS: Debian 10
Compiler: GCC 8.3.0
IDE: Code::Blocks

## Possible Solution
I suspect the culprit is `typeof`, maybe because of the version of GCC I'm using.
Replacing `typeof(&U::parse)*` with `decltype(&U::parse)` seems to work fine (also I didn't manage to get everything to compile yet).
If it works indeed, I think it is a better implementation anyway as `decltype` is C++11 whereas `typeof` is GCC-specific (correct me if I'm wrong).

## Possible Implementation
```
// SFINAE test for 'parse' method
template<typename T>
struct HasParse
{
    typedef char yes[1];
    typedef char no [2];
    template<typename U> static yes &check(decltype(&U::parse)); //<-- typeof()* replaced with decltype() here
    template<typename U> static no &check(...);
    static const bool value = sizeof(check<T>(0)) == sizeof(yes);
};
```

**Comment by Gjacquenot** [comment]
Could you provide more details on your configuration?

Travis-ci that performs CI for xdyn runs a docker container based on debian10 and gcc8.3.0 and it compiles fine (Same configuration as the one you have?). See the log [here](https://travis-ci.org/sirehna/xdyn/jobs/575417199#L557)

You can patch the code by forking the project and commit your modification: it will trigger the CI and we will see what happens. Ideally we would like to reproduce the bug with the CI...

**Comment by mcharlou** [comment]
What details do you require exactly ?

I forked the project, modified the code according to my previous suggestion and submitted a pull request.

A reason that might explain the error under a similar configuration is the fact that i did not use all of the compiler flags used in the CMake build. Maybe one of the flags is required for `typeof` to be defined, also the compiler error was not about `typeof` not being defined (but again it could just be a misleading compiler error).

**Comment by mcharlou** [comment]
Changes where committed and successfully pulled.
