### ISSUE TITLE
Wrong matrix multiplication in radiation Damping force model

### ISSUE THREAD

**Issue by mcharlou** [sirehna/xdyn#9]
## Expected Behavior
Matrix multiplication in the force model (inside the convolution of the velocity history with the radiation damping retardation function) should respect mathematical definition of a matrix multiplication.

## Current Behavior
Each line of the matrix is entirely multiplied with the respective velocity, whereas on each line each term should be multiplied with the respective velocity.
This also causes divergence of the simulation in some cases.

## Possible Solution
Correction of the formula.

## Possible Implementation
See merge request for details.

**Comment by CharlesEdouardCady** [comment]
Great work, thanks! We merged this in 4a55d29e4627260569c181f6a9a95f884631b14b.
